### ISSUE TITLE
New sale logs are not able to be viewed.

### ISSUE THREAD

**Issue by mibby** [Phoenix616/ChestShopNotifier#13]
ChestShopNotifier dev 20
http://ci.minebench.de/job/ChestShopNotifier/
ChestShop dev 10
http://ci.dmulloy2.net/job/ChestShop/
PaperSpigot dev 888
https://ci.destroystokyo.com/

@Phoenix616 I'm getting many reports that new sales are not able to be viewed. A few people informed me that they were not able to clear their read history ```/csn clear``` and that their old sales kept coming up. So I manually wiped the sql tables from the database. Now I'm being informed that they are not able to view new sales whatsoever, but the sql tables have new data in them from recent purchases.

Problem with reading the tables, which subsequently causes clearing issues as well?

```
[08:00:28] [Server thread/INFO]: [ChestShopNotifier] Enabling ChestShopNotifier v1.2-SNAPSHOT (build #20)
[08:00:28] [Server thread/INFO]: [ChestShopNotifier] Connecting to the database...
[08:00:28] [Craft Scheduler Thread - 2/INFO]: HikariPool-0 - is starting.
[08:00:28] [Craft Scheduler Thread - 2/INFO]: [ChestShopNotifier] Database connected!
```
```
logging:
  admin-shop: false

notifications:
  notify-on-user-join: true
  delay-seconds: 5

history:
  max-rows: 10

debugging:
  verbose: false

clean-on-startup:
  enabled: false
  parameters: "--older-than 30 --all"
```

**Comment by Phoenix616** [comment]
Should be fixed with the last couple commits.

**Comment by mibby** [comment]
I see it is for the clear command, but what about new purchase logs not being able to be read?

**Comment by Phoenix616** [comment]
Commit 3c6fab7921491a67bd02a63457db3daa3fa990d2 fixed /csn history for me, are you still having issues with it?

**Comment by mibby** [comment]
That seems to have fixed it for me too. Thanks. :)
