### ISSUE TITLE
console spam about ssl?

### ISSUE THREAD

**Issue by chillerkraft** [Phoenix616/ChestShopNotifier#16]
https://pastebin.com/gPpzbme9

**Comment by Phoenix616** [comment]
Please provide some more info about your setup and what exactly makes you think that this is an issue with this plugin.

**Comment by chillerkraft** [comment]
latest spigot latest plugins using server host with mysql
when i remove this plugin the spam goes away

**Comment by Phoenix616** [comment]
Well it's just a warning and not really an error but I understand that it is kinda annoying. It stems from your mysql server using SSL connections by default. I guess we'd need to add support for that now. Not sure if you can disable that default behaviour in MySQL, if so there isn't really an issue as long as it runs on the same machine as your server.

**Comment by chillerkraft** [comment]
k thanks!
