### ISSUE TITLE
language/message

### ISSUE THREAD

**Issue by seema84** [Phoenix616/ChestShopNotifier#18]
can you please add "all" messages/text to the config for customisation?
at the moment i missing some

**Comment by FrankHeijden** [comment]
Added in #19

**Comment by seema84** [comment]
thats not right. 
in #19 he has add "some" messages but not "all"

**Comment by Phoenix616** [comment]
Which messages are you missing @seema84?

**Comment by seema84** [comment]
for example the command usage text

**Comment by Phoenix616** [comment]
I'm not sure what you are talking about? They are [included](https://github.com/Phoenix616/ChestShopNotifier/pull/19/files#diff-ee97532d2d40af21fc87a8fc24cd37c3R60) in his pull request?

**Comment by seema84** [comment]
in my new fresh config i can see only 12 messages

> messages:
  sales: "&c ** You made &f{sales} sales&c since you last checked."
  history-cmd: "&c ** To see them, type &f/csn history&c."
  history-caption: "&dChestShop Notifier // &7Latest Commissions"
  history-empty: "&cNothing to show."
  history-bought: "&a+ &9{player} &7bought &a{count}x&9{item} &f{timeago}&7 ago &a(+{money})"
  history-bought-read: "&a+ &7{player} &8bought &a{count}x&7{item} &7{timeago}&8 ago &a(+{money})"
  history-sold: "&c- &9{player} &7sold you &c{count}x&9{item} &f{timeago}&7 ago &c(-{money})"
  history-sold-read: "&c- &7{player} &8sold you &c{count}x&7{item} &7{timeago}&8 ago &c(-{money})"
  history-footer-page: "&c- Page &f{current}&c/&f{pages}&6 - &7/csn history <page>"
  history-footer-clear: "&f- &cTo remove all old entries, type /csn clear"
  history-clear: "&cHistory cleared! New sales will continue to be recorded."
  history-marked-read: "&cUnread entries marked read!"

**Comment by Phoenix616** [comment]
His pull request has not been merged yet. You will have to build his fork if you want his features.

**Comment by seema84** [comment]
Oh Right. You will not add this request in the main line?

**Comment by Phoenix616** [comment]
I will once all the issues with it are fixed. Just take a look at the comments on his PR.

**Comment by seema84** [comment]
ok, some days i can wait. (I have been waiting for several years)

**Comment by seema84** [comment]
thanks
