### ISSUE TITLE
item name repeated in /csn history

### ISSUE THREAD

**Issue by NullCase** [Phoenix616/ChestShopNotifier#23]
Hi @Phoenix616 

One of my players submitted this as a bug. Just thought I'd pass it on.

https://cdn.discordapp.com/attachments/478964418659614741/512799742246387712/unknown.png

**Versions:**
ChestShopNotifier 1.2.1
Chestshop Build 106
Paper Build 441

**Comment by Phoenix616** [comment]
Please try out the latest [development build](https://ci.minebench.de/job/ChestShopNotifier/), you are running a pretty old version.
