### ISSUE TITLE
Translation of "history-bought" is not always called correctly

### ISSUE THREAD

**Issue by TheoRetisch1** [Phoenix616/ChestShopNotifier#24]
Hejo,

I have translated the message "history-bought". If you enter /csn history for the first time after a transaction, the translation will be displayed correctly. If you call /csn history again the english version of the message will be displayed. From all other messages the translation of the config is always called correctly. 'Simple' but amazing plugin btw, player love it :)

Paper 1.12.2 #1594
ChestShop 3.9.2 SNAPSHOT Build 78
ChestShopNotifier 1.3.0-SNAPSHOT (build#36)

**Comment by Phoenix616** [comment]
You have to translate both the [unread and read lines](https://github.com/Phoenix616/ChestShopNotifier/blob/master/src/main/resources/config.yml#L34-L37).

**Comment by TheoRetisch1** [comment]
Omg I generated a very old config file and didn't saw that. Thanks for your help!
