### ISSUE TITLE
sqlite support

### ISSUE THREAD

**Issue by seema84** [Phoenix616/ChestShopNotifier#25]
can you please add a sqlite support?

**Comment by phemmer** [comment]
I've created a PR over at #28 to add support for this.
I've also created a custom release on my fork with a build available: https://github.com/phemmer/ChestShopNotifier/releases/download/1.2.1-sqlite/ChestShopNotifier.jar

Just put the following in your config:
```
database:
  type: sqlite
```

**Comment by seema84** [comment]
Is sqlite now fully supported (also to convert the data from mysql to sqlite and vice versa)? 
The description still says that only mysql is supported.

**Comment by Phoenix616** [comment]
Looks like the PR didn't update the readme and I missed that on the review, thanks for noting that!
