### ISSUE TITLE
Not a bug, more a question than anything else.

### ISSUE THREAD

**Issue by 1ronChef** [Phoenix616/ChestShopNotifier#27]
I understand this is more a ME problem, than an issue above all else.
Is there any way to make it so it uses the rando account 'SERVER' as the server tax account rather than an actual players account?

17.01 19:02:29 [Server] WARN Server economy account setting 'SERVER' doesn't seem to be the name of a known player! Please log in at least once in order for the server economy account to work.

**Comment by Phoenix616** [comment]
This is nothing to do with this plugin but with ChestShop and its config itself.

The only thing somewhat related that this plugin can do is log the admin shop (`logging.admin-shop` in the config)
