### ISSUE TITLE
Java crashed on /csn clear

### ISSUE THREAD

**Issue by adamlaughlin** [Phoenix616/ChestShopNotifier#29]
Thanks for asking me to open an issue, I was afraid this plugin wasn't being maintained.
I was trying the commands out for the first time and issued /csn clear; immediately I received an error in the console saying that the Java runtime had crashed.

This is the most recent release of CSN, and a PaperMC server running build 509 (1.13.2).
Java 1.8 (Java HotSpot(TM) 64-Bit Server VM 25.191-b12), Host: Linux 3.11.0-26-generic (amd64)

If it helps, there was nothing to clear at the time.  Perhaps this use case hasn't been tested before.  I haven't tried running the plugin long enough to clear a list which actually exists.

**Comment by Phoenix616** [comment]
Can you provide the error and the exact version of the plugin that you are using? (Because if you mean the version released on spigot then that's not the latest development build, see the buildserver linked in the description and readme for these)

**Comment by adamlaughlin** [comment]
No, when Java crashes it stops logging everything.  Once you clear the console, it's over.
It doesn't refer to a line of Java anyway, it refers to a frame of C code, it wouldn't be very useful.
No logs were created regarding the plugin.

**Comment by Phoenix616** [comment]
I figured as much, guess I hoped there would be something. Do you log MySQL queries by any chance? Would be interesting to see if it even hit the database server.

Also I still need the exact plugin version as the latest dev builds have a good amount of difference from the releases.

**Comment by adamlaughlin** [comment]
I found the Jenkins you were referring to - this build working as you say, thank you!  I'm glad you responded, I was convinced you stopped work on this in October 2016.  I hope you also update the resource on Spigot.  At a glance it's really easy for me to assume a plugin didn't make it past 1.13.

The only glitch left is the presence of /csn read in the help text.  It's part of the usage argument in plugin.yml too but doesn't really appear anywhere else.
